Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-12, with the labels that each got.

#287 doc: .github: updated download to v4
  .github/workflows/zoomin-publish-dev.yml
  .github/workflows/zoomin-publish.yml
Labels: documentation

#288 doc: thingy:91 X support
  doc/docs/index.md
Labels: documentation, doc required

#289 Feat/nrfcloud thingy91x
  Changelog.md
  package.json
  resources/devices/firmware/thingy91x_nrfcloud_multi_service.zip
  src/features/flows/reducers.tsx
  src/features/flows/thingy91x/Evaluate.tsx
  src/features/flows/thingy91x/index.ts
  src/features/flows/thingy91x/thingy91xSlice.ts
Labels: doc not required, ui not required

#290 docs: thingy is not a dk so use 'device'
  src/features/flows/thingy91x/Evaluate.tsx
Labels: doc not required, ui not required

#291 docs: edit changelog
  Changelog.md
Labels: doc not required, ui not required

#292 docs: add punctuation to entries missing it
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9161/index.ts
  src/features/flows/thingy91x/index.ts
Labels: doc not required, ui not required

#293 docs: use version v1.2.0 and add release date
  Changelog.md
  package.json
Labels: doc not required, ui not required
