Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-01, with the labels that each got.

#138 doc: add one page intro and github workflows
  .github/workflows/zoomin-publish-dev.yml
  .github/workflows/zoomin-publish.yml
  .github/workflows/zoomin.yml
  doc/docs/index.md
  doc/mkdocs.yml
  doc/zoomin/custom.properties
  doc/zoomin/tags.yml
Labels: documentation

#150 Add label check workflow
  .github/workflows/labels.yml
Labels: doc not required

#151 docs: added changelog entry
  Changelog.md
Labels: doc not required

#152 feat: use reusable workflow from shared
  .github/workflows/labels.yml
Labels: doc required

#154 fix: only select and go next for known devices
  src/features/steps/connect/Select.tsx
Labels: doc not required

#155 Refactor/cleaner get config function
  src/app/StepStepper.tsx
  src/features/device/deviceGuides.tsx
  src/features/steps/Apps.tsx
  src/features/steps/Evaluate.tsx
  src/features/steps/Info.tsx
  src/features/steps/Learn.tsx
  src/features/steps/program/SelectFirmware.tsx
  src/features/steps/verify/Verification.tsx
Labels: doc not required
