Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-02, with the labels that each got.

#157 Fix/small fixes
  Changelog.md
  src/features/steps/program/Error.tsx
  src/features/steps/program/programEffects.tsx
Labels: doc not required

#160 refactor: typo
  src/features/steps/connect/Detect.tsx
Labels: doc not required

#161 style: use font-height trick to make sure the text is aligned tight
  src/app/StepStepper.tsx
  src/common/Main.tsx
  src/common/listSelect/MultipleSelect.tsx
  src/common/listSelect/RadioSelect.tsx
  src/features/steps/finish/Finish.tsx
  src/features/steps/finish/RealFinish.tsx
Labels: doc not required

#162 refactor: use a proper button and remove the unnecessary clickFunctions
  src/common/Copy.tsx
Labels: doc not required

#164 feat: log to logger instead of console
  src/features/device/deviceLib.ts
  src/features/steps/Apps.tsx
  src/features/steps/finish/Feedback.tsx
Labels: doc not required

#159 Feat/notice box
  Changelog.md
  src/common/NoticeBox.tsx
  src/features/steps/connect/Detect.tsx
  src/features/steps/program/Error.tsx
  src/features/steps/program/programEffects.tsx
  src/features/steps/program/programSlice.tsx
  src/features/steps/verify/Verification.tsx
Labels: doc not required

#167 feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#168 feat: update engine version
  package.json
Labels: doc not required, ui not required

#169 Docs/changelog and supported device fix
  Changelog.md
  package.json
Labels: doc not required, ui not required

#170 feat: update at command links
  src/features/device/pca10090.json
  src/features/device/pca10153.json
  src/features/device/pca10171.json
Labels: doc not required, ui not required

#171 Docs/changelog
  Changelog.md
Labels: doc not required, ui not required

#172 doc: update supported devices list
  doc/docs/index.md
Labels: documentation, doc required

#173 docs: fix changelog date
  Changelog.md
Labels: doc not required, ui not required

#174 feat: add images for 9151 DK
  resources/devices/images/9151Cores.png
  resources/devices/images/9151DK.png
Labels: doc not required, ui not required

#175 fix: update firmware so at host library is part of firmware
  resources/devices/firmware/nrf9151dk_asset_tracker_v2_debug_2024-01-19_f9e71cd3.hex
Labels: doc not required, ui not required

#176 Add parameters when opening VS Code
  src/features/device/deviceGuides.tsx
  src/features/device/pca10090.json
  src/features/device/pca10153.json
  src/features/device/pca10171.json
  src/features/steps/develop/OpenVsCode.test.ts
  src/features/steps/develop/OpenVsCode.tsx
Labels: doc required, ui not required

#177 docs: lower engine version
  Changelog.md
  package.json
Labels: doc required, ui not required

#179 docs: up version
  package.json
Labels: doc not required, ui not required
