Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-07, with the labels that each got.

#201 fix: update outdated or incorrect links
  src/features/device/pca10090.json
  src/features/steps/develop/CLI.tsx
Labels: documentation, doc required

#203 feat: Add SimCard step for 9151
  Changelog.md
  src/features/flows/nRF9151/SimCard.tsx
  src/features/flows/nRF9151/index.ts
Labels: doc required, ui required

#204 refactor: rename flow slice inside redux
  src/app/store.ts
  src/features/flow/flowSlice.ts
Labels: doc not required, ui not required

#205 fix: if flow step undefined it's Connect
  src/features/flow/index.tsx
Labels: doc not required, ui not required

#206 Fix/wrong buttons verify
  src/common/steps/verify/Verification.tsx
  src/common/steps/verify/verificationSlice.ts
Labels: doc not required, ui not required

#207 refactor: extract formatATResponse to be reusable
  src/common/formatATResponse.ts
  src/common/steps/verify/Verification.tsx
Labels: doc not required, ui not required

#208 fix: verify still had old state even when a new fw was programmed
  src/common/steps/verify/verificationSlice.ts
Labels: doc not required, ui not required

#212 fix: reset choice when selecting device
  src/common/steps/stepReducers.ts
Labels: doc not required, ui not required

#213 feat: update all firmwares
  resources/devices/firmware/nrf9151dk_asset_tracker_v2_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9151dk_asset_tracker_v2_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9151dk_modem_shell_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9151dk_modem_shell_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9151dk_nrfcloud_multi_service_coap_debug_2024-05-08_eef645c4.hex
  resources/devices/firmware/nrf9151dk_nrfcloud_multi_service_coap_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9151dk_serial_lte_modem_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9151dk_serial_lte_modem_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9160dk_asset_tracker_v2_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9160dk_asset_tracker_v2_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9160dk_modem_shell_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9160dk_modem_shell_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9160dk_serial_lte_modem_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9160dk_serial_lte_modem_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9161dk_asset_tracker_v2_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9161dk_asset_tracker_v2_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9161dk_modem_shell_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9161dk_modem_shell_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9161dk_nrfcloud_multi_service_coap_debug_2024-05-08_eef645c4.hex
  resources/devices/firmware/nrf9161dk_nrfcloud_multi_service_coap_debug_2024-07-04_20471118.hex
  resources/devices/firmware/nrf9161dk_serial_lte_modem_debug_2024-03-13_af2b60d2.hex
  resources/devices/firmware/nrf9161dk_serial_lte_modem_debug_2024-07-04_20471118.hex
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#215 style: Update 9151 sim card style
  src/features/flows/nRF9151/SimCard.tsx
Labels: doc required, ui not required

#217 feat: add sim card step for 9161
  Changelog.md
  src/features/flows/nRF9161/SimCard.tsx
Labels: doc required, ui not required

#218 Style/nrf9151 sim
  src/common/Main.tsx
  src/features/flows/nRF9151/SimCard.tsx
Labels: doc not required, ui not required

#219 feat: update to latest shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#214 feat: add custom evaluate step for 9151 mss sample
  src/app/store.ts
  src/common/steps/Evaluate.tsx
  src/features/flow/index.tsx
  src/features/flows/nRF9151/Evaluate.tsx
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9151/nrf9151Slice.ts
  src/features/flows/nRF9161/Evaluate.tsx
  src/features/flows/nRF9161/index.ts
  src/features/flows/nRF9161/nrf9161Slice.ts
  src/features/flows/reducers.tsx
Labels: doc required, ui required

#216 Feat/at auto read
  Changelog.md
  src/common/steps/verify/Verification.tsx
  src/common/steps/verify/index.tsx
  src/features/flows/nRF9151/Evaluate.tsx
  src/features/flows/nRF9161/Evaluate.tsx
Labels: doc not required, ui not required

#220 Feat/programming revamp
  src/common/steps/program/Error.tsx
  src/common/steps/program/Program.tsx
  src/common/steps/program/Success.tsx
  src/common/steps/program/index.tsx
  src/common/steps/program/programEffects.tsx
  src/common/steps/program/programSlice.tsx
Labels: doc not required, ui not required

#221 Fix/various
  src/common/steps/Evaluate.tsx
  src/common/steps/program/Program.tsx
Labels: doc not required, ui not required

#222 fix: only show skip when programming failed
  src/common/steps/program/Program.tsx
Labels: doc not required, ui not required

#223 feat: unify 91 sim card step same in name and add for 9161
  src/features/flows/nRF9151/SIM.tsx
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/SIM.tsx
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/SIM.tsx
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#224 Fix VSCode screen: render hooks
  src/common/steps/develop/OpenVsCode.tsx
Labels: doc not required, ui not required
