Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-11, with the labels that each got.

#272 Release 1.0.1: prepare
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#273 feat: use device info name instead of pca number
  src/features/flow/connect/Select.tsx
  src/features/flow/index.tsx
  src/features/flows/index.tsx
  src/features/flows/nRF52/index.ts
  src/features/flows/nRF52833/index.ts
  src/features/flows/nRF52840/index.ts
  src/features/flows/nRF5340/index.ts
  src/features/flows/nRF54L15/index.ts
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#274 Feat/program overhaul
  src/common/steps/program/Program.tsx
  src/common/steps/program/ProgressIndicators.tsx
  src/common/steps/program/SelectFirmware.tsx
  src/common/steps/program/index.tsx
  src/common/steps/program/programEffects.tsx
  src/common/steps/program/programSlice.tsx
  src/features/device/deviceLib.ts
  src/features/device/deviceSlice.ts
  src/features/flows/nRF52/index.ts
  src/features/flows/nRF52833/index.ts
  src/features/flows/nRF52840/index.ts
  src/features/flows/nRF5340/index.ts
  src/features/flows/nRF54L15/index.ts
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#277 doc: rename app + other edits
  README.md
  doc/docs/index.md
  doc/mkdocs.yml
  doc/zoomin/custom.properties
Labels: documentation, doc required

#278 Fix/handle program errors
  src/common/steps/program/programEffects.tsx
Labels: doc not required, ui not required

#279 style: handle case of 4 progress steps causing overflow
  src/common/steps/program/ProgressIndicators.tsx
Labels: doc not required, ui not required

#280 style: update modem fw link and link text to reflect version
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#282 .github: update zoomin.yml to use upload v4
  .github/workflows/zoomin.yml
Labels: documentation, doc required

#276 feat: add thingy91x support
  Changelog.md
  package-lock.json
  package.json
  resources/devices/firmware/thingy91x_hello.nrfcloud.zip
  resources/devices/firmware/thingy91x_modem_shell.zip
  resources/devices/firmware/thingy91x_nrfcloud_multi_service.zip
  resources/devices/firmware/thingy91x_serial_lte_modem.zip
  resources/devices/images/Thingy91X.png
  src/common/steps/program/Program.tsx
  src/common/steps/program/programEffects.tsx
  src/common/steps/program/programSlice.tsx
  src/features/device/deviceSlice.ts
  src/features/flows/index.tsx
  src/features/flows/thingy91x/SIM.tsx
  src/features/flows/thingy91x/index.ts
Labels: doc not required, ui not required

#283 fix: various fixes and edits
  package-lock.json
  package.json
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/index.ts
  src/features/flows/thingy91x/index.ts
Labels: doc not required, ui not required

#284 Fix/programming
  src/common/steps/program/programEffects.tsx
Labels: doc not required, ui not required

#285 Docs/version and link
  Changelog.md
  src/features/flows/thingy91x/index.ts
Labels: doc not required, ui not required

#286 Update changelog for v1.1.0
  Changelog.md
Labels: doc required, ui not required
