Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-04, with the labels that each got.

#190 doc: replace infocenter links
  src/features/device/pca10090.json
  src/features/device/pca10153.json
  src/features/device/pca10171.json
Labels: documentation, doc required

#191 doc: fix one remaining Infocenter link
  src/features/device/pca10090.json
  src/features/device/pca10153.json
  src/features/device/pca10171.json
Labels: documentation, doc required

#194 Fix/various
  Changelog.md
  src/app/App.tsx
  src/features/steps/verify/Verification.tsx
Labels: doc not required, ui required

#195 docs: update version
  package.json
Labels: doc not required, ui not required

#193 doc: update readme
  README.md
Labels: documentation, doc required, ui not required
