Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-10, with the labels that each got.

#261 fix: update broken 54 fw
  resources/devices/firmware/nrf54l15dk_lbs.hex
Labels: doc not required, ui not required

#262 fix: update broken uart firmware for 54
  resources/devices/firmware/nrf54l15dk_peripheral_uart.hex
Labels: doc not required, ui not required

#263 fix: don't use shorthand comparison when value can be zero
  src/common/Resource.tsx
Labels: doc not required, ui not required

#264 refactor: remove unused json
  src/features/device/pca10153.json
  src/features/device/pca10171.json
Labels: doc not required, ui not required

#265 feat: make fw links optional
  src/common/steps/program/ProgressIndicators.tsx
  src/common/steps/program/programSlice.tsx
Labels: doc not required, ui not required

#267 docs: up version and set release date
  Changelog.md
  package.json
Labels: doc not required, ui not required

#268 Feat/better connect
  src/features/flow/connect/Detect.tsx
  src/features/flow/connect/Select.tsx
Labels: doc required, ui not required

#260 doc: add download link
  doc/docs/index.md
Labels: documentation, doc required

#269 Style/5x
  src/common/steps/5xFamilyVerify/Verify.tsx
  src/features/flows/nRF52/index.ts
  src/features/flows/nRF52833/index.ts
  src/features/flows/nRF52840/index.ts
  src/features/flows/nRF5340/index.ts
  src/features/flows/nRF54L15/index.ts
Labels: doc required, ui required

#270 Update nrfutil to v2.6.4
  Changelog.md
  package-lock.json
  package.json
  src/common/sendATCommands.ts
Labels: doc not required, ui not required

#271 fix: forgot to rename the ref to sample after renaming sample
  src/features/flows/nRF52/index.ts
  src/features/flows/nRF52833/index.ts
  src/features/flows/nRF52840/index.ts
  src/features/flows/nRF5340/index.ts
  src/features/flows/nRF54L15/index.ts
Labels: doc not required, ui not required
