Repository NordicSemiconductor/pc-nrfconnect-quickstart, pull requests merged in 2024-09, with the labels that each got.

#236 fix: disconnecting the device before programming caused incorrect beh…
  src/common/steps/program/Program.tsx
  src/common/steps/program/programEffects.tsx
Labels: doc not required, ui not required

#237 Fix/various
  src/common/steps/91FamilyVerify/index.tsx
  src/features/flows/nRF9161/SIM.tsx
Labels: doc not required, ui not required

#238 docs: change wording and set release date
  Changelog.md
Labels: doc not required, ui not required

#239 docs: up version
  Changelog.md
  package.json
Labels: doc not required, ui not required

#247 feat: new 91x samples with different tags
  resources/devices/firmware/nrf9151dk_asset_tracker.hex
  resources/devices/firmware/nrf9151dk_modem_shell.hex
  resources/devices/firmware/nrf9151dk_nrfcloud_multi_service.hex
  resources/devices/firmware/nrf9151dk_serial_lte_modem.hex
  resources/devices/firmware/nrf9160dk_asset_tracker.hex
  resources/devices/firmware/nrf9160dk_modem_shell.hex
  resources/devices/firmware/nrf9160dk_serial_lte_modem.hex
  resources/devices/firmware/nrf9161dk_asset_tracker.hex
  resources/devices/firmware/nrf9161dk_modem_shell.hex
  resources/devices/firmware/nrf9161dk_nrfcloud_multi_service.hex
  resources/devices/firmware/nrf9161dk_serial_lte_modem.hex
  src/features/flows/nRF9151/index.ts
  src/features/flows/nRF9160/index.ts
  src/features/flows/nRF9161/index.ts
Labels: doc not required, ui not required

#248 fix: wrong app name
  src/features/flows/nRF54L15/index.ts
Labels: doc not required, ui not required

#249 fix: disable continue in specific case
  src/features/flow/connect/Select.tsx
Labels: doc not required, ui not required

#250 feat: add checkmark when 5x verify succeeded
  src/common/steps/5xFamilyVerify/Verify.tsx
Labels: doc not required, ui not required

#251 Feat/auto select
  src/features/flow/connect/Select.tsx
Labels: doc not required, ui not required

#252 Fix/auto select
  Changelog.md
  src/features/flow/connect/Select.tsx
Labels: doc required, ui not required

#253 feat: add picture to 54 info step
  resources/devices/images/54L15DK.png
  src/features/flows/nRF54L15/index.ts
Labels: doc not required, ui not required

#254 fix: only autoselect supported devices
  src/features/flow/connect/Select.tsx
Labels: doc not required, ui not required

#255 feat: remove ble app from 54 flow
  src/features/flows/nRF54L15/index.ts
Labels: doc not required, ui not required

#241 docs: add nRF54L to supported devices
  doc/docs/index.md
Labels: documentation

#256 style: center app descriptions in app step
  src/common/steps/Apps.tsx
Labels: doc not required, ui not required

#258 feat: update/correct learn link for 54
  src/features/flows/nRF54L15/index.ts
Labels: doc not required, ui not required

#235 Feat/nrf52
  Changelog.md
  resources/devices/firmware/nrf52833dk_hello_world.hex
  resources/devices/firmware/nrf52833dk_lbs.hex
  resources/devices/firmware/nrf52833dk_peripheral_uart.hex
  resources/devices/firmware/nrf52840dk_hello_world.hex
  resources/devices/firmware/nrf52840dk_lbs.hex
  resources/devices/firmware/nrf52840dk_peripheral_uart.hex
  resources/devices/firmware/nrf52dk_hello_world.hex
  resources/devices/firmware/nrf52dk_lbs.hex
  resources/devices/firmware/nrf52dk_peripheral_uart.hex
  resources/devices/images/52833DK.png
  resources/devices/images/52833DKTech.png
  resources/devices/images/52840DK.png
  resources/devices/images/52840DKTech.png
  resources/devices/images/52DK.png
  resources/devices/images/52DKTech.png
  src/features/flows/index.tsx
  src/features/flows/nRF52/index.ts
  src/features/flows/nRF52833/index.ts
  src/features/flows/nRF52840/index.ts
Labels: doc required, ui not required
